### ISSUE TITLE
大佬这个可以支持Vue-cli嘛，也就是有ajax请求那种

### ISSUE THREAD

**Issue by liushuai05** [zbysir/go-vue-ssr#4]
大概看了一下源码，这个好像不是Vue的ssr方案，看起来更像是一款看起来长得很像Vue的golang模版解析（golang Template）解决方案，因为我如果要引入第三方包估计会比较困难，如果在cli下只需要一个npm install 或者 yarn add即可实现。不知道他是否支持Vue-cli编译后的代码实现ssr呢 大佬

**Comment by zbysir** [comment]
是的，和前端定义的 SSR 概念不太一样，前端的 SSR 是实现了同构的，也就是前端后端公用同一套代码，而这个仓库只是将 vue 的模版语法在 golang 上实现了，只能做到用 vue 模板渲染出 HTML，不涉及到前端部分，确实是 golang Template，你理解得对。

不支持编译后的代码，因为编译之后就不是 vue 模板了，而是 render 函数，纯函数需要 Node （或 goja）环境才能运行。

你的需求是什么？如果真的要 SSR，用 Nuxt.js 即可。
